# Generated by Django 4.1.7 on 2023-03-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closequestions',
            name='radioText',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='closeQuestions',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='openQuestions',
        ),
        migrations.AddField(
            model_name='closequestions',
            name='mainQuizze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quizzes', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='openquestions',
            name='mainQuizze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quizzes', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radiotext',
            name='questionText',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.closequestions', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='radiotext',
            name='radioText',
            field=models.CharField(max_length=255, verbose_name='Ответ'),
        ),
    ]
