# Generated by Django 4.1.7 on 2023-03-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_customers_gifts_quizzes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='closequestions',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='openquestions',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
