# Generated by Django 4.1.7 on 2023-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_closequestions_order_openquestions_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
