# Generated by Django 4.1.7 on 2023-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_customers_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
    ]
