# Generated by Django 4.1.7 on 2023-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_customers_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='token',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
