# Generated by Django 4.1.7 on 2023-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_remove_customers_token_quizzes_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='closequestions',
            name='type',
            field=models.CharField(blank=True, default='radio', editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openquestions',
            name='type',
            field=models.CharField(blank=True, default='open', editable=False, max_length=255, null=True),
        ),
    ]
